/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedEdgeFinderRouteImport } from './routes/_authenticated/edge-finder'
import { Route as AuthenticatedEquityRouteImport } from './routes/_authenticated/equity'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedMilestonesRouteImport } from './routes/_authenticated/milestones'
import { Route as AuthenticatedMissedTradesRouteImport } from './routes/_authenticated/missed-trades'
import { Route as AuthenticatedMissedTradesAnalysisRouteImport } from './routes/_authenticated/missed-trades-analysis'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as AuthenticatedChartLabChartRouteImport } from './routes/_authenticated/chart-lab.$chart'
import { Route as AuthenticatedDiaryNotebookRouteImport } from './routes/_authenticated/diary.notebook'
import { Route as AuthenticatedDiarySessionsRouteImport } from './routes/_authenticated/diary.sessions'
import { Route as AuthenticatedReportsAnnualRouteImport } from './routes/_authenticated/reports.annual'
import { Route as AuthenticatedReportsCalendarRouteImport } from './routes/_authenticated/reports.calendar'
import { Route as AuthenticatedReportsChartBookRouteImport } from './routes/_authenticated/reports.chart-book'
import { Route as AuthenticatedReportsMonthlyRouteImport } from './routes/_authenticated/reports.monthly'
import { Route as AuthenticatedSettingsSectionRouteImport } from './routes/_authenticated/settings.$section'
import { Route as AuthenticatedStrategyLabAlternativesRouteImport } from './routes/_authenticated/strategy-lab.alternatives'
import { Route as AuthenticatedStrategyLabBacktesterRouteImport } from './routes/_authenticated/strategy-lab.backtester'
import { Route as AuthenticatedStrategyLabSimulatorRouteImport } from './routes/_authenticated/strategy-lab.simulator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEdgeFinderRoute = AuthenticatedEdgeFinderRouteImport.update({
  id: '/edge-finder',
  path: '/edge-finder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquityRoute = AuthenticatedEquityRouteImport.update({
  id: '/equity',
  path: '/equity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMilestonesRoute = AuthenticatedMilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMissedTradesRoute =
  AuthenticatedMissedTradesRouteImport.update({
    id: '/missed-trades',
    path: '/missed-trades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMissedTradesAnalysisRoute =
  AuthenticatedMissedTradesAnalysisRouteImport.update({
    id: '/missed-trades-analysis',
    path: '/missed-trades-analysis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChartLabChartRoute =
  AuthenticatedChartLabChartRouteImport.update({
    id: '/chart-lab/$chart',
    path: '/chart-lab/$chart',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiaryNotebookRoute =
  AuthenticatedDiaryNotebookRouteImport.update({
    id: '/diary/notebook',
    path: '/diary/notebook',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiarySessionsRoute =
  AuthenticatedDiarySessionsRouteImport.update({
    id: '/diary/sessions',
    path: '/diary/sessions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsAnnualRoute =
  AuthenticatedReportsAnnualRouteImport.update({
    id: '/reports/annual',
    path: '/reports/annual',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsCalendarRoute =
  AuthenticatedReportsCalendarRouteImport.update({
    id: '/reports/calendar',
    path: '/reports/calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsChartBookRoute =
  AuthenticatedReportsChartBookRouteImport.update({
    id: '/reports/chart-book',
    path: '/reports/chart-book',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsMonthlyRoute =
  AuthenticatedReportsMonthlyRouteImport.update({
    id: '/reports/monthly',
    path: '/reports/monthly',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsSectionRoute =
  AuthenticatedSettingsSectionRouteImport.update({
    id: '/settings/$section',
    path: '/settings/$section',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStrategyLabAlternativesRoute =
  AuthenticatedStrategyLabAlternativesRouteImport.update({
    id: '/strategy-lab/alternatives',
    path: '/strategy-lab/alternatives',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStrategyLabBacktesterRoute =
  AuthenticatedStrategyLabBacktesterRouteImport.update({
    id: '/strategy-lab/backtester',
    path: '/strategy-lab/backtester',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStrategyLabSimulatorRoute =
  AuthenticatedStrategyLabSimulatorRouteImport.update({
    id: '/strategy-lab/simulator',
    path: '/strategy-lab/simulator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/edge-finder': typeof AuthenticatedEdgeFinderRoute
  '/equity': typeof AuthenticatedEquityRoute
  '/home': typeof AuthenticatedHomeRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/milestones': typeof AuthenticatedMilestonesRoute
  '/missed-trades': typeof AuthenticatedMissedTradesRoute
  '/missed-trades-analysis': typeof AuthenticatedMissedTradesAnalysisRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/share/$token': typeof ShareTokenRoute
  '/chart-lab/$chart': typeof AuthenticatedChartLabChartRoute
  '/diary/notebook': typeof AuthenticatedDiaryNotebookRoute
  '/diary/sessions': typeof AuthenticatedDiarySessionsRoute
  '/reports/annual': typeof AuthenticatedReportsAnnualRoute
  '/reports/calendar': typeof AuthenticatedReportsCalendarRoute
  '/reports/chart-book': typeof AuthenticatedReportsChartBookRoute
  '/reports/monthly': typeof AuthenticatedReportsMonthlyRoute
  '/settings/$section': typeof AuthenticatedSettingsSectionRoute
  '/strategy-lab/alternatives': typeof AuthenticatedStrategyLabAlternativesRoute
  '/strategy-lab/backtester': typeof AuthenticatedStrategyLabBacktesterRoute
  '/strategy-lab/simulator': typeof AuthenticatedStrategyLabSimulatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/edge-finder': typeof AuthenticatedEdgeFinderRoute
  '/equity': typeof AuthenticatedEquityRoute
  '/home': typeof AuthenticatedHomeRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/milestones': typeof AuthenticatedMilestonesRoute
  '/missed-trades': typeof AuthenticatedMissedTradesRoute
  '/missed-trades-analysis': typeof AuthenticatedMissedTradesAnalysisRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/share/$token': typeof ShareTokenRoute
  '/chart-lab/$chart': typeof AuthenticatedChartLabChartRoute
  '/diary/notebook': typeof AuthenticatedDiaryNotebookRoute
  '/diary/sessions': typeof AuthenticatedDiarySessionsRoute
  '/reports/annual': typeof AuthenticatedReportsAnnualRoute
  '/reports/calendar': typeof AuthenticatedReportsCalendarRoute
  '/reports/chart-book': typeof AuthenticatedReportsChartBookRoute
  '/reports/monthly': typeof AuthenticatedReportsMonthlyRoute
  '/settings/$section': typeof AuthenticatedSettingsSectionRoute
  '/strategy-lab/alternatives': typeof AuthenticatedStrategyLabAlternativesRoute
  '/strategy-lab/backtester': typeof AuthenticatedStrategyLabBacktesterRoute
  '/strategy-lab/simulator': typeof AuthenticatedStrategyLabSimulatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/edge-finder': typeof AuthenticatedEdgeFinderRoute
  '/_authenticated/equity': typeof AuthenticatedEquityRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/milestones': typeof AuthenticatedMilestonesRoute
  '/_authenticated/missed-trades': typeof AuthenticatedMissedTradesRoute
  '/_authenticated/missed-trades-analysis': typeof AuthenticatedMissedTradesAnalysisRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/share/$token': typeof ShareTokenRoute
  '/_authenticated/chart-lab/$chart': typeof AuthenticatedChartLabChartRoute
  '/_authenticated/diary/notebook': typeof AuthenticatedDiaryNotebookRoute
  '/_authenticated/diary/sessions': typeof AuthenticatedDiarySessionsRoute
  '/_authenticated/reports/annual': typeof AuthenticatedReportsAnnualRoute
  '/_authenticated/reports/calendar': typeof AuthenticatedReportsCalendarRoute
  '/_authenticated/reports/chart-book': typeof AuthenticatedReportsChartBookRoute
  '/_authenticated/reports/monthly': typeof AuthenticatedReportsMonthlyRoute
  '/_authenticated/settings/$section': typeof AuthenticatedSettingsSectionRoute
  '/_authenticated/strategy-lab/alternatives': typeof AuthenticatedStrategyLabAlternativesRoute
  '/_authenticated/strategy-lab/backtester': typeof AuthenticatedStrategyLabBacktesterRoute
  '/_authenticated/strategy-lab/simulator': typeof AuthenticatedStrategyLabSimulatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/analytics'
    | '/edge-finder'
    | '/equity'
    | '/home'
    | '/journal'
    | '/milestones'
    | '/missed-trades'
    | '/missed-trades-analysis'
    | '/plans'
    | '/portfolio'
    | '/share/$token'
    | '/chart-lab/$chart'
    | '/diary/notebook'
    | '/diary/sessions'
    | '/reports/annual'
    | '/reports/calendar'
    | '/reports/chart-book'
    | '/reports/monthly'
    | '/settings/$section'
    | '/strategy-lab/alternatives'
    | '/strategy-lab/backtester'
    | '/strategy-lab/simulator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/analytics'
    | '/edge-finder'
    | '/equity'
    | '/home'
    | '/journal'
    | '/milestones'
    | '/missed-trades'
    | '/missed-trades-analysis'
    | '/plans'
    | '/portfolio'
    | '/share/$token'
    | '/chart-lab/$chart'
    | '/diary/notebook'
    | '/diary/sessions'
    | '/reports/annual'
    | '/reports/calendar'
    | '/reports/chart-book'
    | '/reports/monthly'
    | '/settings/$section'
    | '/strategy-lab/alternatives'
    | '/strategy-lab/backtester'
    | '/strategy-lab/simulator'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/analytics'
    | '/_authenticated/edge-finder'
    | '/_authenticated/equity'
    | '/_authenticated/home'
    | '/_authenticated/journal'
    | '/_authenticated/milestones'
    | '/_authenticated/missed-trades'
    | '/_authenticated/missed-trades-analysis'
    | '/_authenticated/plans'
    | '/_authenticated/portfolio'
    | '/share/$token'
    | '/_authenticated/chart-lab/$chart'
    | '/_authenticated/diary/notebook'
    | '/_authenticated/diary/sessions'
    | '/_authenticated/reports/annual'
    | '/_authenticated/reports/calendar'
    | '/_authenticated/reports/chart-book'
    | '/_authenticated/reports/monthly'
    | '/_authenticated/settings/$section'
    | '/_authenticated/strategy-lab/alternatives'
    | '/_authenticated/strategy-lab/backtester'
    | '/_authenticated/strategy-lab/simulator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/edge-finder': {
      id: '/_authenticated/edge-finder'
      path: '/edge-finder'
      fullPath: '/edge-finder'
      preLoaderRoute: typeof AuthenticatedEdgeFinderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equity': {
      id: '/_authenticated/equity'
      path: '/equity'
      fullPath: '/equity'
      preLoaderRoute: typeof AuthenticatedEquityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/milestones': {
      id: '/_authenticated/milestones'
      path: '/milestones'
      fullPath: '/milestones'
      preLoaderRoute: typeof AuthenticatedMilestonesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missed-trades': {
      id: '/_authenticated/missed-trades'
      path: '/missed-trades'
      fullPath: '/missed-trades'
      preLoaderRoute: typeof AuthenticatedMissedTradesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missed-trades-analysis': {
      id: '/_authenticated/missed-trades-analysis'
      path: '/missed-trades-analysis'
      fullPath: '/missed-trades-analysis'
      preLoaderRoute: typeof AuthenticatedMissedTradesAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chart-lab/$chart': {
      id: '/_authenticated/chart-lab/$chart'
      path: '/chart-lab/$chart'
      fullPath: '/chart-lab/$chart'
      preLoaderRoute: typeof AuthenticatedChartLabChartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diary/notebook': {
      id: '/_authenticated/diary/notebook'
      path: '/diary/notebook'
      fullPath: '/diary/notebook'
      preLoaderRoute: typeof AuthenticatedDiaryNotebookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diary/sessions': {
      id: '/_authenticated/diary/sessions'
      path: '/diary/sessions'
      fullPath: '/diary/sessions'
      preLoaderRoute: typeof AuthenticatedDiarySessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/annual': {
      id: '/_authenticated/reports/annual'
      path: '/reports/annual'
      fullPath: '/reports/annual'
      preLoaderRoute: typeof AuthenticatedReportsAnnualRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/calendar': {
      id: '/_authenticated/reports/calendar'
      path: '/reports/calendar'
      fullPath: '/reports/calendar'
      preLoaderRoute: typeof AuthenticatedReportsCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/chart-book': {
      id: '/_authenticated/reports/chart-book'
      path: '/reports/chart-book'
      fullPath: '/reports/chart-book'
      preLoaderRoute: typeof AuthenticatedReportsChartBookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/monthly': {
      id: '/_authenticated/reports/monthly'
      path: '/reports/monthly'
      fullPath: '/reports/monthly'
      preLoaderRoute: typeof AuthenticatedReportsMonthlyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/$section': {
      id: '/_authenticated/settings/$section'
      path: '/settings/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof AuthenticatedSettingsSectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/strategy-lab/alternatives': {
      id: '/_authenticated/strategy-lab/alternatives'
      path: '/strategy-lab/alternatives'
      fullPath: '/strategy-lab/alternatives'
      preLoaderRoute: typeof AuthenticatedStrategyLabAlternativesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/strategy-lab/backtester': {
      id: '/_authenticated/strategy-lab/backtester'
      path: '/strategy-lab/backtester'
      fullPath: '/strategy-lab/backtester'
      preLoaderRoute: typeof AuthenticatedStrategyLabBacktesterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/strategy-lab/simulator': {
      id: '/_authenticated/strategy-lab/simulator'
      path: '/strategy-lab/simulator'
      fullPath: '/strategy-lab/simulator'
      preLoaderRoute: typeof AuthenticatedStrategyLabSimulatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedEdgeFinderRoute: typeof AuthenticatedEdgeFinderRoute
  AuthenticatedEquityRoute: typeof AuthenticatedEquityRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedMilestonesRoute: typeof AuthenticatedMilestonesRoute
  AuthenticatedMissedTradesRoute: typeof AuthenticatedMissedTradesRoute
  AuthenticatedMissedTradesAnalysisRoute: typeof AuthenticatedMissedTradesAnalysisRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedChartLabChartRoute: typeof AuthenticatedChartLabChartRoute
  AuthenticatedDiaryNotebookRoute: typeof AuthenticatedDiaryNotebookRoute
  AuthenticatedDiarySessionsRoute: typeof AuthenticatedDiarySessionsRoute
  AuthenticatedReportsAnnualRoute: typeof AuthenticatedReportsAnnualRoute
  AuthenticatedReportsCalendarRoute: typeof AuthenticatedReportsCalendarRoute
  AuthenticatedReportsChartBookRoute: typeof AuthenticatedReportsChartBookRoute
  AuthenticatedReportsMonthlyRoute: typeof AuthenticatedReportsMonthlyRoute
  AuthenticatedSettingsSectionRoute: typeof AuthenticatedSettingsSectionRoute
  AuthenticatedStrategyLabAlternativesRoute: typeof AuthenticatedStrategyLabAlternativesRoute
  AuthenticatedStrategyLabBacktesterRoute: typeof AuthenticatedStrategyLabBacktesterRoute
  AuthenticatedStrategyLabSimulatorRoute: typeof AuthenticatedStrategyLabSimulatorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedEdgeFinderRoute: AuthenticatedEdgeFinderRoute,
  AuthenticatedEquityRoute: AuthenticatedEquityRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedMilestonesRoute: AuthenticatedMilestonesRoute,
  AuthenticatedMissedTradesRoute: AuthenticatedMissedTradesRoute,
  AuthenticatedMissedTradesAnalysisRoute:
    AuthenticatedMissedTradesAnalysisRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedChartLabChartRoute: AuthenticatedChartLabChartRoute,
  AuthenticatedDiaryNotebookRoute: AuthenticatedDiaryNotebookRoute,
  AuthenticatedDiarySessionsRoute: AuthenticatedDiarySessionsRoute,
  AuthenticatedReportsAnnualRoute: AuthenticatedReportsAnnualRoute,
  AuthenticatedReportsCalendarRoute: AuthenticatedReportsCalendarRoute,
  AuthenticatedReportsChartBookRoute: AuthenticatedReportsChartBookRoute,
  AuthenticatedReportsMonthlyRoute: AuthenticatedReportsMonthlyRoute,
  AuthenticatedSettingsSectionRoute: AuthenticatedSettingsSectionRoute,
  AuthenticatedStrategyLabAlternativesRoute:
    AuthenticatedStrategyLabAlternativesRoute,
  AuthenticatedStrategyLabBacktesterRoute:
    AuthenticatedStrategyLabBacktesterRoute,
  AuthenticatedStrategyLabSimulatorRoute:
    AuthenticatedStrategyLabSimulatorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
